### PR TITLE
Added MvcEvent to EVENT_LOAD event handler

### PR DESCRIPTION
**Pull request by duepi**
It can be useful to have MvcEvent even in the LOAD event.
It's a simple edit that will give usa a little big plus ;)

### CODE REVIEW

**Comment by bramstroker** [comment]
@duepi Thanks for PR. Could you please fix the unit tests accordingly?

**Comment by duepi** [comment]
@bramstroker Thanks for the merge; **keep it up!**

**Comment by duepi** [comment]
@bramstroker just one more question. I run `composer clear-cache` and then `composer update ` but still don't get my edits; do i miss something ?

**Comment by bramstroker** [comment]
@duepi I have not tagged a new release yet. Will do that after I forward proof the module towards ZF3 (hopefully this week).
You can however require "dev-master" in your composer to use the latest version of the master branch, this should work when you have minimum-stability: dev.

**Comment by duepi** [comment]
@bramstroker in effect, this is what i have done; thank you

**Pull request merged**
